name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  # Make sure CI fails on all warnings, including Clippy lints
  RUSTFLAGS: "-Dwarnings"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt
    - uses: Swatinem/rust-cache@v2
    - name: Run clippy
      run: cargo clippy --all-targets -p osm-pbf-parquet
    - name: Run cargo fmt
      run: cargo fmt -p osm-pbf-parquet -- --check

  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - uses: astral-sh/setup-uv@v5
    - name: Build
      run: cargo build --release -p osm-pbf-parquet
    - name: Run unit tests
      run: cargo test -p osm-pbf-parquet
    - name: Install osmium
      run: sudo apt-get update && sudo apt-get install -y osmium-tool
    - name: Prepare and run test
      run: ./test.sh
      working-directory: ./osm-pbf-parquet/test
    - name: Benchmark
      run: cargo bench -p osm-pbf-parquet
